# This file exposes the graphql schema and documents to the graphql.vscode-graphql and other compatible IDE extensions
schema: "./src/lib/graphql/schema.graphql"
documents: "src/lib/graphql/**/*.{js,ts,jsx,tsx}"
