# This file exposes the graphql schema and documents to the graphql.vscode-graphql and other compatible IDE extensions
schema: "./lib/graphql/schema.graphql"
documents: "lib/graphql/**/*.{js,ts,jsx,tsx}"
