attributes:
  icon:
    label: 'Choose an icon for this menu item'
    description: ''
    options:
      facebook: Facebook
      twitter: Twitter
      linkedin: Linkedin
      wunder: Wunder
    default_value: ''
  container_class:
    label: 'Container class(es)'
    description: 'CSS class for the menu list item (&lt;li&gt;). Separate multiple classes by space.'
